### ISSUE TITLE
The 'prophet' method is ignored by abed

### ISSUE THREAD

**Issue by simontrapp** [alan-turing-institute/TCPDBench#10]
Hello,
I am using a modified version of TCPDBench, but with a similar abed_conf.py file. I added other methods, but did not delete old ones. The best/default methods of "prohet" are in the METHODS list and the commands are defined in COMMANDS and PARAMS. 

**The problem**: In my "abed_results" folder, there are no prophet folders or results for any of my datasets. Therefore its line in the aggregated wide latex table is empty (that's how I recognized the error).

I didn't notice any prophet-related errors during runtime of the experiments, is there a bug that prevents prophet from running?
Best regards,
Simon

**Comment by GjjvdBurg** [comment]
Hi Simon,

Sorry to hear you're getting an error. Can you post or link to your ``abed_conf.py`` file?

P.S.: To debug, you can run ``abed reload_tasks`` to reload the task list and then run ``abed explain_tbd_tasks`` to list the tasks that still need to be done. If there's an error running Prophet, the relevant tasks will still be listed as to be completed.

**Comment by simontrapp** [comment]
Thanks for the response!
I am using this file: https://github.com/simontrapp/TCPDBench/blob/development/abed_conf.py

I am going to test your suggestions in the next few days and then report back!

**Comment by GjjvdBurg** [comment]
I don't immediately see anything odd in your ``abed_conf.py`` file. Have you checked that Prophet was installed correctly? When you run ``abed local`` any errors will be printed to the screen, so be sure to check that as well. Good luck and let me know what you find!

**Comment by simontrapp** [comment]
Hello again, I figured out the problem: Since I am using different datasets with different names, prophet throws an error when checking against the hard-coded names. Is there a reason why only these specific datasets are allowed for prophet? When deleting the name-checks, it works just fine. I committed the changes to my repo, if you want to take a look.
Anyways, thanks for the help regarding the debugging, you helped me out a lot!
Best regards,
Simon

**Comment by GjjvdBurg** [comment]
Thanks for the update @simontrapp! I had forgotten about these hard-coded dataset names in the prophet wrapper, I'll make sure to document that in the README as well. The dataset names are there to allow Prophet to use the actual frequencies of the data to automatically determine the seasonality components to include, but as you've noticed this is not strictly necessary.

Glad you got it working!
