### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by moritzteichner** [alan-turing-institute/TCPDBench#14]
Hello,

for my research, I am planning to extend the benchmark with my own CPD algorithm and new data sets.
Will this again trigger an execution of the existing algorithms on the existing data sets, or will the “missing” values just be added and included in creating the output files?
And when this is not the case, will this again trigger an optimization of existing algorithms on existing data sets?

Lastly, will an execution of existing algorithms happen, if I just change the annotations for existing data sets?
Thanks in advance.

Moritz

**Comment by GjjvdBurg** [comment]
Hi Moritz,

Once you've added your method and dataset configurations to the `abed_conf.py` file as described in the readme, you can use the instructions [here](https://github.com/alan-turing-institute/TCPDBench#running-experiments) to "register" these methods/datasets with abed. This will generate a task list for the remaining methods, assuming that you have the result files for the existing ones (it simply checks for the existence of particular files). You can then run `abed explain_tbd_tasks` to see what tasks remain to be done, and if all is well that should be the ones for your method/dataset.

To run the analysis scripts on your method/dataset, you will need to add them [here](https://github.com/alan-turing-institute/TCPDBench/blob/master/analysis/scripts/common.py) too. Running `make results` after that should generate the output figures and tables.

If you change the annotation of existing datasets, you'll need to run `make results` as well.

Hope this helps!

**Comment by moritzteichner** [comment]
That is exactly what I needed! 
Thanks very much for the information.
Cheers,

Moritz
