### ISSUE TITLE
Got this error when ran the docker file

### ISSUE THREAD

**Issue by ashutosh1807** [alan-turing-institute/TCPDBench#2]
Installing collected packages: pip, setuptools
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
  Attempting uninstall: setuptools
    Found existing installation: setuptools 45.2.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'setuptools'. No files were found to uninstall.
Successfully installed pip-20.1 setuptools-46.4.0
ln: failed to create symbolic link 'pip': File exists
The command '/bin/sh -c apt-get install -y --no-install-recommends 	python3 	python3-dev 	python3-tk 	python3-pip &&     pip3 install --no-cache-dir --upgrade pip setuptools && 	echo "alias python='python3'" >> /root/.bash_aliases && 	echo "alias pip='pip3'" >> /root/.bash_aliases && 	cd /usr/local/bin && ln -s /usr/bin/python3 python && 	cd /usr/local/bin && ln -s /usr/bin/pip3 pip &&     pip install virtualenv abed' returned a non-zero code: 1

**Comment by GjjvdBurg** [comment]
Thanks for the reporting this issue @ashutosh1807! I believe it is now fixed in master, could you give it another try? Thanks!

**Comment by ashutosh1807** [comment]
Works now! Thanks @GjjvdBurg

**Comment by GjjvdBurg** [comment]
Good to hear, thanks for confirming @ashutosh1807!
