### ISSUE TITLE
Python lib

### ISSUE THREAD

**Issue by hushchyn-mikhail** [alan-turing-institute/TCPDBench#3]
Hi,

Thanks for this repo and your article. They are very cute! It would also be nice if you created a python library that provides the ability to run all the CPD methods from your article on custom data.

**Comment by GjjvdBurg** [comment]
Hi @hushchyn-mikhail, thank you for your interest in our work!

Creating such a Python library will likely be quite a bit of work, but it should be straightforward to add a new dataset or method to the experiments. For instance, we recently added a [zero method](https://github.com/alan-turing-institute/TCPDBench/commit/f3b6797e3b4a2dd1be46d3c8c59b2d74d1a129bf) to the benchmark.

I'll add some instructions to the repository on how to add a new dataset or method to the benchmark.

**Comment by hushchyn-mikhail** [comment]
Thanks for the fast response.

In particularly, we are interested in to run your CPD methods on our datasets and get outputs of these algorithms. I guess, it is possible somehow to do, but the instructions will make it easier :)

**Comment by GjjvdBurg** [comment]
Hi @hushchyn-mikhail,

I've added additional instructions to the readme on how to extend the benchmark with new methods and datasets. Does this answer your question?

**Comment by hushchyn-mikhail** [comment]
Great! 
Thanks a lot for this.
